name: Release portable Linux PyTorch Wheels

on:
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx110X-dgpu
          - gfx1151
          - gfx120X-all
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx94X-dcgpu
      release_type:
        description: The type of release to build ("nightly", "prerelease", or "dev")
        type: choice
        options:
          - dev
          - nightly
          - prerelease
        default: dev
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: choice
        options:
          - v2
          - v3/whl
        default: v2
      s3_staging_subdir:
        description: "Staging subdirectory to push the wheels for test"
        type: choice
        options:
          - v2-staging
          - v3/whl-staging
        default: v2-staging
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: choice
        options:
          - https://d25kgig7rdsyks.cloudfront.net/v2
          - https://rocm.prereleases.amd.com/whl
          - https://rocm.nightlies.amd.com/v2
        default: https://d25kgig7rdsyks.cloudfront.net/v2
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        type: choice
        options:
          - https://d25kgig7rdsyks.cloudfront.net/v2-staging
          - https://rocm.prereleases.amd.com/whl-staging
          - https://rocm.nightlies.amd.com/v2-staging
        default: https://d25kgig7rdsyks.cloudfront.net/v2-staging
      rocm_version:
        description: ROCm version to pip install
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Otherwise, uses the default branch."
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release PyTorch | ${{ inputs.amdgpu_family }} | Python ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12", 3.13]
        pytorch_version: ["release/2.7", "release/2.9", "nightly"]
        include:
          - pytorch_version: release/2.7
            pytorch_patchset: "rocm_2.7"
          - pytorch_version: release/2.9
            pytorch_patchset: rocm_2.9
          - pytorch_version: nightly
            pytorch_patchset: "nightly"

    uses: ROCm/TheRock/.github/workflows/build_portable_linux_pytorch_wheels.yml@users/marbre/therock-releases
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: ${{ matrix.python_version }}
      release_type: ${{ inputs.release_type }}
      s3_subdir: ${{ inputs.s3_subdir }}
      s3_staging_subdir: ${{ inputs.s3_staging_subdir }}
      cloudfront_url: ${{ inputs.cloudfront_url }}
      cloudfront_staging_url: ${{ inputs.cloudfront_staging_url }}
      rocm_version: ${{ inputs.rocm_version }}
      pytorch_version: ${{ matrix.pytorch_version }}
      pytorch_patchset: ${{ matrix.pytorch_patchset }}
      repository: "ROCm/TheRock"
      ref: ${{ inputs.ref || '' }}
