name: Release Windows packages

on:
  # Trigger manually (typically to test the workflow or manually build a release [candidate])
  workflow_dispatch:
    inputs:
      release_type:
        description: The type of build version to produce ("nightly", "prerelease", or "dev")
        type: choice
        options:
          - dev
          - nightly
          - prerelease
        default: dev
      package_suffix:
        type: string
      s3_subdir:
        description: "Subdirectory to push the packages"
        type: choice
        options:
          - v2
          - v3/whl
        default: v2
      s3_staging_subdir:
        description: "Staging subdirectory to push the packages"
        type: choice
        options:
          - v2-staging
          - v3/whl-staging
        default: v2-staging
      families:
        description: "Comma separated list of AMD GPU families, e.g. `gfx115X`"
        type: string
      prerelease_version:
        description: "(Optional) Number of the prerelease"
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Otherwise, uses the default branch."
        type: string
#   # Trigger on a schedule to build nightly release candidates.
#   schedule:
#     # Runs at 04:00 AM UTC, which is 8:00 PM PST (UTC-8)
#     - cron: '0 04 * * *'

permissions:
  contents: read

jobs:
  linux_packages:
    name: Build
    uses: ROCm/TheRock/.github/workflows/release_windows_packages.yml@users/marbre/therock-releases
    secrets: inherit
    with:
      release_type: ${{ inputs.release_type || 'nightly' }}
      package_suffix: ""
      s3_subdir: ${{ inputs.s3_subdir || 'v2' }}
      s3_staging_subdir: ${{ inputs.s3_staging_subdir || 'v2-staging' }}
      families: ${{ inputs.families || '' }}
      prerelease_version: ${{ inputs.prerelease_version || '' }}
      repository: "ROCm/TheRock"
      ref: ${{ inputs.ref || '' }}
    permissions:
      actions: write
      contents: write
      id-token: write
